enable-magisk-update = false

parallel-jobs = 3

patches-version = "dev"
integrations-version = "dev"

[YouTube-RV]
app-name = "YouTube"
rv-brand = "RV"
included-patches = "'Change header'"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Photos-RV]
app-name = "Photos"
rv-brand = "RV"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
arch = "arm64-v8a"

[YouTube-RVX]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX"
excluded-patches = "'Custom branding name for YouTube'"
included-patches = "'Custom header for YouTube' 'MaterialYou'"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Music-RVX]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX"
excluded-patches = "'Custom branding name for YouTube Music'"
included-patches = "'Custom header for YouTube Music'"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
